dependencies = []
incompatibilities = []

[metadata]
id = "com.example.mod"
version = "1.0.0"
title = "Example Mod"
description = "Example mod for spiderheck"
authors = [
    "Me!"
]
game_version = 1.6